#!/bin/bash

#PBS -l walltime=00:05:00

#PBS -l nodes=1:ppn=4
#PBS -l pmem=1gb
#PBS -u fbenurea
#PBS -q inria

#PBS -o /home/fbenurea/logs/${PBS_JOBNAME}.out
#PBS -e /home/fbenurea/logs/${PBS_JOBNAME}.err

#PBS -m a
#PBS -M fabien.benureau@gmail.com

cd $PBS_O_WORKDIR

# replace "monkeys" by your pyenv's virtual environment name.
# if you do not have pyenv, python version will be unchanged.
export PYENV_VERSION=monkeys

python run_job.py ${PBS_ARRAYID}

unset PYENV_VERSION
